### ISSUE TITLE
barchart client breaks when changing condition term2 to 'most recent grade'

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1925]
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22diaggrp%22},%22term2%22:{%22id%22:%22Neurology%20System%22}}],%22nav%22:{%22activeTab%22:1}})

err: TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at negateTermLabel (barchart.js:950:17)
    at generatePvalueTable (barchart.js:904:79)

**Comment by gavrielm** [comment]
Also, when condition is term1 and set to `most recent grade`, the total sample count is higher than the number of patients, but it should be the same.
