### ISSUE TITLE
hover over gene row label in hierCluster errors out

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#655]
it's hardcoded for accessing mutation data. only do it when this.parent.chartType is not hierCluster

matrix.interactivity.js:1483 Uncaught TypeError: Cannot read properties of undefined (reading 'color')
    at self.<computed> (matrix.interactivity.js:1483:53)
    at SVGGElement.<anonymous> (on.js:3:14)

**Comment by xzhou82** [comment]
please fix before tomorrow

**Comment by xzhou82** [comment]
https://github.com/stjude/proteinpaint/pull/665
